repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
      - id: docker-compose-check
        # setting the name is purely aesthetic, I prefer it being lowercase
        name: docker-compose-check
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or: [ javascript, css ]
  - repo: local
    hooks:
      - id: pylint
        types: [ python ]
        name: pylint
        entry: pylint --rcfile=.pylintrc
        language: python
      - id: eslint
        name: eslint
        entry: bash -c "cd sudan-art/react-frontend && npx eslint --fix 'src/**/*.js'"
        language: node
