# Reference https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: thisisabadpasswordresetforproduction
  django:
    build: ./sudan-art/django-backend
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_LOGGING: ${DJANGO_LOGGING}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    volumes:
      - ./sudan-art/django-backend:/home/worker/app/django-backend
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build:
      context: ./sudan-art/react-frontend
      dockerfile: Dockerfile-dev
    volumes:
      - ./sudan-art/react-frontend:/app/react-frontend
    ports:
      - 3000:3000