# Reference https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.9'

services:
  django:
    build: ./sudan-art/django-backend
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DJANGO_CORS_ORIGINS: ${DJANGO_CORS_ORIGINS}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_LOGGING: ${DJANGO_LOGGING}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    ports:
      - "8000:8000"
  frontend:
    build: ./sudan-art/react-frontend
    ports:
      - "80:80"