# Generated by Django 4.0 on 2021-12-14 10:00

import django.core.validators
from django.db import migrations, models
import sudan_art.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artist', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Artist names must be between 3 to 30 characters long. The following characters are allowed: arabic letters and numbers, english letters and numbers, underscores, hyphens, and a space.', regex='^[ء-ي٠-٩ a-zA-Z0-9]{3,30}$')])),
                ('tags', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Tags must be between 1 to 90 characters long. The following characters are allowed: arabic letters and numbers, english letters and numbers, a comma.', regex='^[ء-ي٠-٩a-zA-Z0-9,]{1,90}$')])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=sudan_art.models.image_absolute_path)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
