# Generated by Django 4.0 on 2022-03-05 15:12

import sudan_art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudan_art", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="high_res_image",
            field=models.ImageField(upload_to=sudan_art.models.rename_highres),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="thumbnail",
            field=models.ImageField(upload_to=sudan_art.models.rename_thumbnail),
        ),
    ]
