# Generated by Django 4.0 on 2021-12-14 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudan_art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='tags',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Tags must be between 1 to 90 characters long. The following characters are allowed: arabic letters and numbers, english letters and numbers, a comma, and a space.', regex='^[ء-ي٠-٩a-zA-Z0-9, ]{1,90}$')]),
        ),
    ]
