# Generated by Django 4.0 on 2022-04-16 00:04

import sudan_art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudan_art", "0002_alter_artwork_high_res_image_alter_artwork_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="tags",
            field=models.CharField(
                max_length=60, validators=[sudan_art.models.validate_tags]
            ),
        ),
    ]
