# Generated by Django 4.0 on 2022-04-16 00:55

import sudan_art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudan_art", "0003_alter_artwork_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="tags",
            field=models.CharField(
                max_length=250, validators=[sudan_art.models.validate_tags]
            ),
        ),
    ]
