# Generated by Django 4.0 on 2022-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudan_art", "0004_alter_artwork_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="url",
            field=models.URLField(default=""),
        ),
    ]
